version: '3.7'

services:


  mongodb:
    image: mongo:latest
    restart: on-failure
    container_name: mongo
#    volumes:
#    - ./services/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
#    - ./services/mongodb/mongo-volume:/data/db
    ports:
      - 27017:27017
    expose:
      - 27017
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
